version: '3.9'
services:
  website:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"

networks:
  default:
    driver: bridge

volumes:
  redis-data: {}
