version: "3.9"
services:
  api:
    build: ./backend
    restart: unless-stopped
  website:
    build: ./frontend
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  db-data: {}
