version: '3.9'
services:
  redis:
    env_file:
      - .env.production
  website:
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/ssl/skystats:/etc/ssl/skystats
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data: {}
  caddy-config: {}
