version: '3.9'
services:
    api:
        env_file:
            - ./backend/.env
        ports:
            - 8080:8080
    website:
        env_file:
            - frontend/.env
        ports:
            - 3033:3000
    database:
        env_file:
            - ./backend/.env
        ports:
            - 5432:5432
